name: Generate Tokens On Input

on:
  push:
    paths:
      - "style-dictionary/build/figma-tokens.json"

jobs:
  generate_tokens:
    runs-on: macos-latest
    steps:
      - name: Transform design tokens
        run: "yarn && yarn run generate-tokens"
      - name: Commit Generated Platform Deliverables
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update platform deliverables
