name: Transform Figma Tokens

on: push
  # push:
  #   paths:
  #     - "style-dictionary/source/figma-tokens.json"

jobs:
  transform_figma_tokens:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install Node Dependencies
        run: npm install
      - name: Build Style Dictionary
        run: yarn run generate-tokens
      - name: Commit Generated Platform Deliverables
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update platform deliverables
